--
--Create Table
--
CREATE TABLE `TABLE_MASTER` (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,    
    `TABLE_KEY` VARCHAR(255) NOT NULL,
    `DISPLAY_NAME` VARCHAR(255) NOT NULL,    
    `ICON` VARCHAR(255) NOT NULL,
    `DESCRIPTION` VARCHAR(255) DEFAULT NULL,
    `CREATED_BY` VARCHAR(45) DEFAULT NULL,
    `CREATED_AT` DATETIME DEFAULT NULL,
    `LAST_UPDATED_BY` VARCHAR(45) DEFAULT NULL,
    `LAST_UPDATED_AT` DATETIME DEFAULT NULL,
    PRIMARY KEY (`ID`)
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

CREATE TABLE `NUMBER_COLUMN_MASTER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `COLUMN_KEY` varchar(255) NOT NULL,
  `DISPLAY_NAME` varchar(255) NOT NULL,
  `ICON` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL,
  `LAST_UPDATED_BY` varchar(45) DEFAULT NULL,
  `LAST_UPDATED_AT` datetime DEFAULT NULL,
  `TABLE_ID` bigint(20) DEFAULT NULL,
  `IS_NEGATIVE_ALLOWED` bit(1) DEFAULT b'0',
  `MIN_ALLOWED` int(11) DEFAULT NULL,
  `MAX_ALLOWED` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `TABLE_ID_idx` (`TABLE_ID`),
  CONSTRAINT `NUMBER_TABLE_ID` FOREIGN KEY (`TABLE_ID`) REFERENCES `table_master` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `STRING_COLUMN_MASTER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `COLUMN_KEY` varchar(255) NOT NULL,
  `DISPLAY_NAME` varchar(255) NOT NULL,
  `ICON` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL,
  `LAST_UPDATED_BY` varchar(45) DEFAULT NULL,
  `LAST_UPDATED_AT` datetime DEFAULT NULL,
  `TABLE_ID` bigint(20) DEFAULT NULL,
  `IS_MULTILINE` bit(1) DEFAULT NULL,
  `MAX_LENGTH_ALLOWED` int(2) DEFAULT NULL,
  `MIN_LENGTH_ALLOWED` int(2) DEFAULT NULL,
  `REGEX_PATTERN` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `TABLE_ID_idx` (`TABLE_ID`),
  CONSTRAINT `TABLE_ID` FOREIGN KEY (`TABLE_ID`) REFERENCES `table_master` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

