--
--Create Table
--
CREATE TABLE `deletenow`.`table_master` (
  `ID` varchar(20) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(4096) DEFAULT NULL,
  `DISPLAY_NAME` varchar(255) NOT NULL,
  `ICON` varchar(255) DEFAULT NULL,
  `LAST_UPDATED_BY` varchar(45) DEFAULT NULL,
  `LAST_UPDATED_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `deletenow`.`number_column_master` (
  `ID` varchar(20) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `DISPLAY_NAME` varchar(255) NOT NULL,
  `ICON` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(4096) DEFAULT NULL,
  `LAST_UPDATED_BY` varchar(45) DEFAULT NULL,
  `LAST_UPDATED_AT` datetime DEFAULT NULL,
  `TABLE_ID` varchar(20) DEFAULT NULL,
  `IS_NEGATIVE_ALLOWED` bit(1) DEFAULT b'0',
  `MIN_ALLOWED` int(11) DEFAULT NULL,
  `MAX_ALLOWED` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `TABLE_ID_idx` (`TABLE_ID`),
  CONSTRAINT `NUMBER_TABLE_ID` FOREIGN KEY (`TABLE_ID`) REFERENCES `table_master` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `deletenow`.`string_column_master` (
  `ID` varchar(20) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `DISPLAY_NAME` varchar(255) NOT NULL,
  `ICON` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `LAST_UPDATED_BY` varchar(45) DEFAULT NULL,
  `LAST_UPDATED_AT` datetime DEFAULT NULL,
  `TABLE_ID` varchar(20) DEFAULT NULL,
  `IS_MULTILINE` bit(1) DEFAULT NULL,
  `MAX_LENGTH_ALLOWED` int(2) DEFAULT NULL,
  `MIN_LENGTH_ALLOWED` int(2) DEFAULT NULL,
  `REGEX_PATTERN` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `TABLE_ID_idx` (`TABLE_ID`),
  CONSTRAINT `STRING_TABLE_ID` FOREIGN KEY (`TABLE_ID`) REFERENCES `table_master` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


